export const user = {
    name: "Jeff Bezos",
    city: "Albuquerque",
    born: 1964,
    likes: "Being rich",
    twitterLink: "https://twitter.com/jeffbezos",
    img: "https://img-cdn.inc.com/image/upload/w_1920,h_1080,c_fill/images/panoramic/getty_1032942302_dkawzr.jpg",
    twitterName: "JeffBezos",
    companies: [
      "Amazon",
      "The Washington Post",
      "Google share holder",
      "IMBD",
      "Alexa",
      "Blue Origin",
      "Twitch",
      "Zappos",
      "Whole food market",
      "Amazon robotics",
      "Goodreads",
    ],
  };